Finalizando desafio 1 - Produto Simples
he4rt/he4rtoberfest-2022 pull request #1042
Opened 2022-10-12 19:24 UTC by gushecs

2022-10-12 20:01 UTC, matheusth requested changes
Os desafio pede para ler dois valores inteiros, o seu programa está lendo valores de ponto flutuante.

2022-10-12 21:07 UTC, matheusth requested changes
Você está alterando o .gitignore do repositorio, se precisar de um .gitignore você tem que colocar ele na sua pasta do desafio.

2022-10-12 21:33 UTC, gushecs commented
Retornei o gitignore para o estado anterior, mas fica um aviso: Eu havia modificado em um push anterior no desafio 0, nesse havia apenas corrigido porque tinha adicionado ".iml" ao invés de "*.iml". Se for o caso, fica o aviso para que a mudança seja revertida.

2022-10-12 23:22 UTC, matheusth commented
> Retornei o gitignore para o estado anterior, mas fica um aviso: Eu havia modificado em um push anterior no desafio 0, nesse havia apenas corrigido porque tinha adicionado ".iml" ao invés de "*.iml". Se for o caso, fica o aviso para que a mudança seja revertida.

Obrigado por avisar, eu reverti o push do desafio 0, se puder fazer o pull request dele de novo sem alterar o .gitignore do repositorio.

2022-10-13 00:59 UTC, gushecs commented
Mandei novamente o desafio 0. Mudei o .gitignore daqui para ficar igual ao original da fonte também. vou fazer o mesmo pros demais projetos q havia pedido para finalizar.

2022-10-13 23:41 UTC, merged