Finalizando o desafio 0
he4rt/he4rtoberfest-2022 pull request #105
Opened 2022-10-04 12:20 UTC by rodrigobertozzi

2022-10-04 16:48 UTC, alissongdev commented
Olá, @rodrigobertozzi! Peço que adeque a estrutura de pastas do seu desafio de acordo com as [instruções listadas aqui](https://github.com/he4rt/he4rtoberfest-2022#como-participar). É preciso criar uma pasta com o nome da linguagem usada e, dentro dela, outra pasta com o seu username do GitHub, e dentro desta adicionar o seu código e `README.md`. Se precisar de algum apoio, só comentar aqui!

2022-10-04 17:10 UTC, rodrigobertozzi commented
foi com a pasta .vs, tem problema ou tenho que retirar?

2022-10-04 19:28 UTC, Logikoz commented
@rodrigobertozzi sobe ali no gitignore o template do VS.

tem mt arquivo desnecessário ai.

2022-10-04 19:28 UTC, Logikoz requested changes

2022-10-04 19:28 UTC, Logikoz commented on challenges/0-hello-world/c#/rodrigobertozzi/Program.cs
> +Console.WriteLine("Hello, World of he4rtoberfest-2022!");
output não conforme ao desafio.

[ver aqui](https://github.com/he4rt/he4rtoberfest-2022/blob/main/challenges/0-hello-world/readme.md)

2022-10-04 19:32 UTC, Logikoz commented
tbm altera a pasta.

tem que ser apenas o ID do desafio, não o nome.

de:
```challenges/0-hello-world/c#/rodrigobertozzi/Program.cs``` 
para 
```challenges/0/c#/rodrigobertozzi/Program.cs```

2022-10-04 22:47 UTC, rodrigobertozzi commented on challenges/0-hello-world/c#/rodrigobertozzi/Program.cs
> +Console.WriteLine("Hello, World of he4rtoberfest-2022!");
eu subo o .gitigore na pasta do exercicio?

2022-10-05 14:25 UTC, alissongdev requested changes
Parece que subiu a pasta .vs sem querer, pode removê-la?

2022-10-05 19:26 UTC, rodrigobertozzi commented
> Parece que subiu a pasta `.vs` sem querer, pode removê-la?

Acho que agora foi haha

2022-10-05 19:42 UTC, Luisnadachi commented
Salve [rodrigobertozzi](https://github.com/rodrigobertozzi), uma correção também que eu vi aqui que precisa, no PR que você fez acabou removendo o README do desafio ao inves de copiar e colar o model.md na sua pasta e depois renomea-lo.

2022-10-05 20:07 UTC, rodrigobertozzi commented
> Salve [rodrigobertozzi](https://github.com/rodrigobertozzi), uma correção também que eu vi aqui que precisa, no PR que você fez acabou removendo o README do desafio ao inves de copiar e colar o model.md na sua pasta e depois renomea-lo.

coloquei de volta, mas aparentemente ficou com uma alteração

2022-10-05 23:13 UTC, rodrigobertozzi commented
Desculpa esse tanto de commit, mas só tem uma linha diferente e mesmo baixando o arquivo do repo oficial e colocando de novo não fica igual.

2022-10-05 23:46 UTC, eric-vantunes approved these changes

2022-10-06 15:53 UTC, Logikoz approved these changes

2022-10-06 15:54 UTC, Logikoz commented
@alissongdev rever...

2022-10-06 21:57 UTC, alissongdev approved these changes

2022-10-06 21:57 UTC, merged