Finalizando o desafio 5
he4rt/he4rtoberfest-2022 pull request #33
Opened 2022-10-03 23:49 UTC by scush989898

2022-10-04 03:34 UTC, scush989898 commented
o desafio 0 foi feito, o pr dele está um uns 30-40 pra cima deste. Tinha feito o 0 primeiro, mas esqueci de move os arquivos pra pasta com meu nickname, refiz e ja está na lista pra ser aprovado.

2022-10-05 00:48 UTC, naygo approved these changes
Ok!

2022-10-05 01:39 UTC, alissongdev requested changes

2022-10-05 01:39 UTC, alissongdev commented on challenges/5-cobaias/python/scush989898/desafio-5.py
> +print(f"Total: {total} cobais")
Corrigir typo.
```suggestion
print(f"Total: {total} cobaias")
```

2022-10-05 01:45 UTC, scush989898 commented
@alissongdev commitei a sugestão, vlw

2022-10-05 02:11 UTC, alissongdev approved these changes

2022-10-05 14:01 UTC, merged