Finalizando o desafio 3
he4rt/he4rtoberfest-2022 pull request #341
Opened 2022-10-05 12:49 UTC by edurevsky

2022-10-05 12:57 UTC, naygo requested changes
Salve! Um erro, quando um trinângulo é ESQUILATERO está sendo imprimido que ele também é ISOSCELES

2022-10-05 13:55 UTC, edurevsky commented
mas todo triângulo equilátero também é isósceles

2022-10-05 22:11 UTC, naygo approved these changes
Tudo ok agora foi corrigido, porém você tem razão amigo, todo equilatero é isosceles.

2022-10-06 01:30 UTC, LeonardoRafaelDev commented
Ao rodar o codigo percebi que pelo menos aqui tudo retornou o seguinte log
![image](https://user-images.githubusercontent.com/65264908/194193832-cf090673-53f6-412b-8964-ec427f3bacf7.png)
Me corrija caso esta rodando de forma incorreta por favor!

2022-10-06 03:13 UTC, edurevsky commented
> Ao rodar o codigo percebi que pelo menos aqui tudo retornou o seguinte log ![image](https://user-images.githubusercontent.com/65264908/194193832-cf090673-53f6-412b-8964-ec427f3bacf7.png) Me corrija caso esta rodando de forma incorreta por favor!

Não precisa do console.log, a função printTriangleTypes, como pelo nome já diz, faz o papel de logar. O problema é que ela recebe um **objeto**, que é criado com a função makeTriangle.

2022-10-06 03:17 UTC, edurevsky commented
Aliás, o README explica como rodar o código, não entendi o pq você modificou o código pra rodar...

2022-10-07 02:16 UTC, merged