Finalizando o desafio 2
he4rt/he4rtoberfest-2022 pull request #351
Opened 2022-10-05 14:26 UTC by rodrigofmeneses

2022-10-05 23:51 UTC, matheusth requested changes
coloca o dias entre <>, ficando , para passar a ideia de que é para colocar o número de dias no lugar. la em como rodar o desafio.

2022-10-05 23:51 UTC, matheusth commented on challenges/2-idade-em-dias/python/rodrigofmeneses/README.md
> +python idade_em_dias.py dias
coloca o dias entre <>, ficando <dias>, para passar a ideia de que é para colocar o número de dias no lugar.

2022-10-06 12:32 UTC, rodrigofmeneses commented on challenges/2-idade-em-dias/python/rodrigofmeneses/README.md
> +python idade_em_dias.py dias
Entendido, obrigado pela sugestão!

2022-10-06 12:53 UTC, matheusth approved these changes

2022-10-06 12:56 UTC, merged