Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #375
Opened 2022-10-05 18:56 UTC by eric-vantunes

Hello World!

2022-10-05 19:42 UTC, alissongdev requested changes
Você deve adicionar a sua pasta ao diretório `challenges/0-hello-world/javascript`.

2022-10-05 20:30 UTC, eric-vantunes commented
Atualizei, não sei se esta correto, caso não.. Poderia me dar uma ajuda ?

2022-10-06 00:02 UTC, gabrielduete commented
> Atualizei, não sei se esta correto, caso não.. Poderia me dar uma ajuda ?

Acredito que tenha que colocar na pasta `javascript` já existente no projeto.

2022-10-06 00:20 UTC, closed without merging

2022-10-06 01:23 UTC, eric-vantunes commented
Salve, @gabrielduete tranquilo ! Agradeço mano, fiz novamente. Acredito que agora foi kkk