Challenges/3/shell/jesusgautamah
he4rt/he4rtoberfest-2022 pull request #388
Opened 2022-10-05 20:40 UTC by JesusGautamah

2022-10-05 22:04 UTC, alissongdev requested changes

2022-10-05 22:04 UTC, alissongdev commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Tive erro nesta linha ao executar o script: 

bash: type_of_triangles.sh: line 13: syntax error near unexpected token `then'
bash: type_of_triangles.sh: line 13: `elif then'

2022-10-05 22:09 UTC, JesusGautamah commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Ok, verificando

2022-10-05 22:13 UTC, JesusGautamah commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
```bash
source type_of_triangles.sh 10.0 2.0 1.0

NAO FORMA TRIANGULO
```

A minha condição que fiz errada?
Qual seria o input?

2022-10-05 22:21 UTC, JesusGautamah commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
```bash
source type_of_triangles.sh 2.0 2.0 3.0
TRIANGULO ACUTANGULO
TRIANGULO ISOSCELES
``
Aqui rodando, dando uma pesquisada

2022-10-05 22:22 UTC, alissongdev commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Na verdade o problema estava no terminal que eu estava usando para executar o script. Porém notei que estes dois casos de testes não estão de acordo com o [desafio](https://github.com/he4rt/he4rtoberfest-2022/tree/main/challenges/3-tipos-de-triangulo#desafio-3):

```
Entrada: 6.0 6.0 10.0
TRIANGULO OBTUSANGULO
TRIANGULO ISOSCELES
```

```
Entrada: 5.0 7.0 2.0
NAO FORMA TRIANGULO
```

2022-10-05 22:26 UTC, JesusGautamah commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Ok, verificando

2022-10-05 22:37 UTC, JesusGautamah commented
Correção do teste realizada

2022-10-05 22:43 UTC, alissongdev commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Ainda não está batendo com os cenários de testes do desafio:

```
Entrada: 7.0 5.0 7.0
TRIANGULO ACUTANGULO
TRIANGULO ISOSCELES
```

```
Entrada: 6.0 6.0 10.0
TRIANGULO OBTUSANGULO
TRIANGULO ISOSCELES
```

```
Entrada: 6.0 6.0 6.0
TRIANGULO ACUTANGULO
TRIANGULO EQUILATERO
```

```
Entrada: 5.0 7.0 2.0
NAO FORMA TRIANGULO
```

2022-10-06 02:39 UTC, JesusGautamah commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Testado todos os inputs, muito obrigado pelos reviews!

2022-10-06 14:27 UTC, alissongdev commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Continuo com erro, mano:

```
> source type_of_triangles.sh 7.0 5.0 7.0
type_of_triangles.sh:46: bad math expression: operand expected at end of string
```

2022-10-07 17:06 UTC, JesusGautamah commented on challenges/3-tipos-de-triangulo/shell/jesusgautamah/type_of_triangles.sh
> +elif then
Tranquilo, consigo revisar hoje pela noite

2022-10-08 21:47 UTC, Luisnadachi commented
Salve [JesusGautamah](https://github.com/JesusGautamah), solicito que revise o código e faço o reenvio dele por conta que estava sendo testado em duas máquinas e os resultados não estavam batendo e dando erros.

2022-10-08 21:47 UTC, closed without merging