Finalizando o Desafio 2
he4rt/he4rtoberfest-2022 pull request #396
Opened 2022-10-05 21:50 UTC by gdiasb

2022-10-05 22:27 UTC, alissongdev requested changes

2022-10-05 22:27 UTC, alissongdev commented on challenges/2-idade-em-dias/java/gdiasb/IdadeEmDias.java
> +    System.out.println(quantidadeAnos + " ano(s) " + quantidadeMeses + ", mes(es) e " + quantidadeDias + " dia(s)");
Pequena correção no output.
```suggestion
    System.out.println(quantidadeAnos + " ano(s), " + quantidadeMeses + " mes(es) e " + quantidadeDias + " dia(s)");
```

2022-10-05 22:38 UTC, paulohgs approved these changes
Desafio está certo e aprovado. Como dica de melhoria, pode tentar ver sobre validação de entrada do usuário para garantir que seu programa irá receber números e caso alguém tente colocar algo diferente, retornar uma mensagem pedindo o valor de forma correta.

2022-10-06 00:18 UTC, gdiasb commented
Alterei o código

2022-10-06 00:24 UTC, matheusth requested changes

2022-10-06 00:24 UTC, matheusth commented on challenges/2-idade-em-dias/java/gdiasb/IdadeEmDias.java
> +    System.out.println(quantidadeAnos + " ano(s) " + quantidadeMeses + " mes(es) e " + quantidadeDias + " dia(s)");
coloca a virgula log depois do `"ano(s)"` ficando 
```java
System.out.println(quantidadeAnos + " ano(s), " + quantidadeMeses + " mes(es) e " + quantidadeDias + " dia(s)");
```

2022-10-06 00:30 UTC, gdiasb commented
Pronto, eita vírgula danada

2022-10-06 00:38 UTC, alissongdev requested changes
Estamos permitindo apenas um desafio por PR. Peço que remova a pasta referente ao desafio 6.

2022-10-06 01:04 UTC, closed without merging