Finalizando desafio 2
he4rt/he4rtoberfest-2022 pull request #400
Opened 2022-10-05 22:53 UTC by Mateussnts

Desafio 2 Idade em dias concluído.

2022-10-05 23:20 UTC, DanielHe4rt requested changes

2022-10-05 23:20 UTC, DanielHe4rt commented on challenges/2-idade-em-dias/java/mateussnts/IdadeEmDias.java
> +        int idade = sc.nextInt();
Senti falta de um texto pro input. Afinal, como eu vou saber o que eu tenho que digitar?

2022-10-05 23:52 UTC, Mateussnts commented on challenges/2-idade-em-dias/java/mateussnts/IdadeEmDias.java
> +        int idade = sc.nextInt();
Realizado update de descrição do input.

2022-10-06 00:03 UTC, matheusth approved these changes

2022-10-06 05:22 UTC, merged