Challenges/6/elixir/citadin
he4rt/he4rtoberfest-2022 pull request #401
Opened 2022-10-05 23:15 UTC by rodrigocitadin

2022-10-05 23:17 UTC, rodrigocitadin commented
pq que sempre que eu commito um novo desafio os outros vão junto e eu tenho que ficar dando revert?

2022-10-06 00:07 UTC, alissongdev requested changes
Tive este erro ao tentar executar o código:

```
iex> Challenge.convert 7650
** (CompileError) iex:1: undefined function iex/0
    (stdlib 3.16.1) lists.erl:1358: :lists.mapfoldl/3
```

2022-10-06 00:08 UTC, alissongdev commented
> pq que sempre que eu commito um novo desafio os outros vão junto e eu tenho que ficar dando revert?

Você está fazendo o `git add` especificando os arquivos que deseja commitar?

2022-10-06 00:18 UTC, rodrigocitadin commented
> > pq que sempre que eu commito um novo desafio os outros vão junto e eu tenho que ficar dando revert?
> 
> Você está fazendo o `git add` especificando os arquivos que deseja commitar?

não, fiz isso agora e funcionou aparentemente

2022-10-06 00:21 UTC, rodrigocitadin commented
> Tive este erro ao tentar executar o código:
> 
> ```
> iex> Challenge.convert 7650
> ** (CompileError) iex:1: undefined function iex/0
>     (stdlib 3.16.1) lists.erl:1358: :lists.mapfoldl/3
> ```

no meu está funcionando, se você tiver digitado o `iex>` no terminal vai dar erro, o `iex>` é apenas para mostrar que a pessoa esta dentro do iex

2022-10-06 00:24 UTC, rodrigocitadin commented
você precisa abrir o `iex` usando `iex "converter_segundos.exs"` e depois digitar `Challenge.convert 5800`

2022-10-06 00:26 UTC, alissongdev commented
Tem razão, eu acabei copiando o `iex>` no segundo comando, por isso deu erro.

2022-10-06 00:29 UTC, alissongdev approved these changes

2022-10-06 00:29 UTC, merged