Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #47
Opened 2022-10-04 01:43 UTC by vit0rr

2022-10-04 13:38 UTC, biantris approved these changes
LGTM

2022-10-04 21:57 UTC, alissongdev requested changes

2022-10-04 21:57 UTC, alissongdev commented on challenges/6-converter-segundos/typescript/vit0rr/index.ts
> +hhmmss(7650);
Possibilite que esse parâmetro possa ser definido pelo usuário de forma dinâmica.

2022-10-04 22:37 UTC, vit0rr commented on challenges/6-converter-segundos/typescript/vit0rr/index.ts
> +hhmmss(7650);
> Possibilite que esse parâmetro possa ser definido pelo usuário de forma dinâmica.

Na descrição dos desafios está dizendo `Input/Args`, [aqui ](https://github.com/he4rt/he4rtoberfest-2022/blob/main/challenges/4-fizz-buzz/readme.md). Então acredito que esteja dentro das regras usar argumentos no meu código

2022-10-04 23:43 UTC, alissongdev approved these changes

2022-10-04 23:45 UTC, vit0rr commented
Safe to merge @Luisnadachi ?

2022-10-05 13:58 UTC, alissongdev commented
Como já foram aceitos outros PRs com esse mesmo padrão, estarei fazendo o merge.

2022-10-05 13:58 UTC, merged