Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #475
Opened 2022-10-06 12:08 UTC by guidani

2022-10-06 12:23 UTC, g-101 requested changes
Arquivo model.md precisa ser renomeado para README.md

2022-10-06 18:13 UTC, guidani commented
Efetuado a correção.

2022-10-06 20:43 UTC, Luisnadachi commented
Salve [guidani](https://github.com/guidani), ainda não consta a correção aqui

2022-10-07 13:47 UTC, g-101 requested changes
Ainda não houve alteração para README.md

2022-10-08 12:26 UTC, laisacsts commented
pr fechado porque alteração solicitada não foi realizada.

2022-10-08 12:26 UTC, closed without merging