Challenges/1/c#/marcosferreira17
he4rt/he4rtoberfest-2022 pull request #487
Opened 2022-10-06 13:40 UTC by MarcosFerreira17

2022-10-07 15:13 UTC, newh2 commented
adiciona um arquivo .gitignore na sua solução, para que possa subir somente os arquivos necessários. 
no Visual Studio, vc abre o prompt e digita dotnet new gitignore e ele ja cria pra você, depois você terá q retirar os arquivos desnecessários da branch. Eu faço assim: 
git rm --cached filename retirando os arquivos do cache
comito as alteraçoes git add filename
depois git commit -m "Adicionando .gitignore"

2022-10-07 15:14 UTC, newh2 commented
O "Hello World está incorreto, o correto é:

Hello He4rtoberfest

2022-10-07 16:38 UTC, MarcosFerreira17 commented
Coloquei o gitignore no mesmo diretorio da solução, porém não entendi o comentario sobre  helloword, esse é o desafio 1

2022-10-08 00:40 UTC, alissongdev requested changes
Considerar as sugestões do @newh2. Note que atualmente o seu PR inclui alterações em 57 arquivos, quando deveria estar subindo apenas as modificações necessárias para o desafio 1.

2022-10-08 12:45 UTC, laisacsts commented
pr fechado porque contém mais de um desafio e uma quantidade excessiva de arquivos.

2022-10-08 12:45 UTC, closed without merging