Desafio #7 finalizado
he4rt/he4rtoberfest-2022 pull request #517
Opened 2022-10-06 15:12 UTC by sarahanduca

2022-10-07 02:57 UTC, pontes-guilherme approved these changes

2022-10-07 03:02 UTC, alissongdev requested changes
Assim como no desafio 5, o código parece desconsiderar a quantidade de casos de testes definida pelo usuário.

2022-10-08 12:49 UTC, fernanduandrade approved these changes
![image](https://user-images.githubusercontent.com/58053397/194708403-44a2d697-62d5-42d6-9abd-e1e3773fbf97.png)
acredito que o outpout esteja correto

2022-10-08 14:56 UTC, alissongdev approved these changes
Boua!

2022-10-08 14:56 UTC, merged