Challenges/2/php/gusttavodev
he4rt/he4rtoberfest-2022 pull request #540
Opened 2022-10-06 18:08 UTC by gusttavodev

2022-10-06 18:25 UTC, maikella commented
![image](https://user-images.githubusercontent.com/97262283/194390231-cf8ff26c-9b78-4836-a670-b067bc984019.png)

fala man, beleza? remova os diretórios relacionados a outros desafios. apenas um desafio por PR.

2022-10-06 18:44 UTC, gusttavodev commented
Resolvido

2022-10-07 01:26 UTC, Luisnadachi requested changes

2022-10-07 01:26 UTC, Luisnadachi commented on challenges/2-idade-em-dias/php/gusttavodev /app.php
> +print_r("{$anos} ano(s)" . PHP_EOL);
Salve gusttavodev, só pedir um ajuste, quando vai retornar no print os valores eles vem quebrados, mas não existe ano, mes e dia quebrado, ai ia pedir um tratamento para isso.

2022-10-08 21:51 UTC, closed without merging