Challenges/2/go/jessicamosouza
he4rt/he4rtoberfest-2022 pull request #554
Opened 2022-10-06 19:23 UTC by jessicamosouza

2022-10-06 19:26 UTC, maikella commented
![image](https://user-images.githubusercontent.com/97262283/194401358-8fe093b2-c504-4688-afb4-a7c65757de1e.png)
fala minha consagrada, beleza? remova os diretórios relacionados a outros desafios. apenas um desafio por PR.

2022-10-07 03:16 UTC, Luisnadachi requested changes
Salve jessicamosouza o PR que você está subindo, ele está com uma remoção do seu readme do desafio 1.

2022-10-07 11:22 UTC, jessicamosouza commented
Olá! Acho que agora está tudo certo :)

2022-10-07 19:10 UTC, Luisnadachi commented
Salve jessicamosouza, ainda esta acontecendo os conflitos e exclusão dos arquivos, o que aconselho você a fazer é restaurar a sua branch ou criar uma do zero e assim fazer o envio dos arquivos do desafio em especifico

2022-10-07 19:58 UTC, closed without merging