fit: solve 03 with rust
he4rt/he4rtoberfest-2022 pull request #557
Opened 2022-10-06 19:46 UTC by gusttavodev

2022-10-06 20:31 UTC, matheusth requested changes

2022-10-06 20:31 UTC, matheusth commented on challenges/3-tipos-de-triangulo/rust/gusttavodev/src/main.rs
> +            Type::ACUTE => println!("ACUTE"),
Tente deixar as saídas igual ao que é pedido no desafio:
TRIANGULO OBTUSANGULO
TRIANGULO ACUTANGULO
TRIANGULO RETANGULO
TRIANGULO EQUILATERO
TRIANGULO ISOSCELES

2022-10-06 20:31 UTC, matheusth commented on challenges/3-tipos-de-triangulo/rust/gusttavodev/src/main.rs
> +            Type::ACUTE => println!("ACUTE"),
e em caso de não formar triangulo imprimir a mensagem  NAO FORMA TRIANGULO em vez de INVALID.

2022-10-07 03:40 UTC, 1pride approved these changes

2022-10-07 10:26 UTC, matheusth approved these changes

2022-10-07 10:29 UTC, merged