Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #559
Opened 2022-10-06 20:04 UTC by digzom

2022-10-07 21:38 UTC, Cyytrus commented on challenges/5-cobaias/elixir/digzom/README.md
> +**Exercicio:** 0 - Hello World
Acho que nessa parte vc se esqueceu de alterar o titulo para `5 - Cobaias` :moyai:

```suggestion
**Exercicio:** 5 - Cobaias
```

2022-10-08 12:42 UTC, fernanduandrade requested changes
salve mano eu testei o código e está dando erro na linha 38
![image](https://user-images.githubusercontent.com/58053397/194708112-5b32d05e-a53d-424e-a4a1-8f4fd739a796.png)
o txt está na forma correta?

2022-10-08 12:42 UTC, fernanduandrade commented
![image](https://user-images.githubusercontent.com/58053397/194708143-a2a53784-282c-4eff-b9bb-c250fdf43183.png)

2022-10-08 13:21 UTC, digzom commented
> 

Você tá dentro da pasta do projeto meu projeto especificamente? Pergunto porque o arquivo do código (`cobaias.exs`) tá dentro da pasta `/elixir/digzom/`, mas no seu print tá só `elixir`.

2022-10-08 13:23 UTC, digzom commented
> salve mano eu testei o código e está dando erro na linha 38 ![image](https://user-images.githubusercontent.com/58053397/194708112-5b32d05e-a53d-424e-a4a1-8f4fd739a796.png) o txt está na forma correta?

Você tá na pasta `elixir/digzom`? O script `cobaias.exs` tá dentro da pasta do meu username, digzom. Pergunto porque no seu print tem só `elixir` ao invés de `elixir/digzom`. Tá correto mesmo?

2022-10-08 13:43 UTC, fernanduandrade commented
era meu local, mas clonei o teu e entrei na branch deu o msm resultado :(
![image](https://user-images.githubusercontent.com/58053397/194710583-fc36835b-236f-451b-9e6c-2d135b9c4d40.png)

2022-10-08 14:59 UTC, digzom commented
> era meu local, mas clonei o teu e entrei na branch deu o msm resultado :( ![image](https://user-images.githubusercontent.com/58053397/194710583-fc36835b-236f-451b-9e6c-2d135b9c4d40.png)

Não faço ideia do que seja. hehe

Vou investigar um pouco.

2022-10-08 15:08 UTC, fernanduandrade commented
blz fico no aguardo aqui 😊

2022-10-08 15:21 UTC, digzom commented
> blz fico no aguardo aqui 😊

Vi que você tá no Windows, e pode ser algo a ver com isso. Tenta rodar com sintaxe pasta.

Algo como:

```bash
elixir .\cobaias.exs .\input.txt
```

2022-10-08 15:38 UTC, fernanduandrade commented
naum foi 😥 ![image](https://user-images.githubusercontent.com/58053397/194715564-bf0ce2bb-90c1-423c-ad60-1bfe499643ce.png)

2022-10-08 18:17 UTC, digzom commented
> naum foi disappointed_relieved ![image](https://user-images.githubusercontent.com/58053397/194715564-bf0ce2bb-90c1-423c-ad60-1bfe499643ce.png)

Putz. Tenho uma pista do que possa ser. Volto mais tarde.

2022-10-08 18:26 UTC, digzom commented
> naum foi disappointed_relieved ![image](https://user-images.githubusercontent.com/58053397/194715564-bf0ce2bb-90c1-423c-ad60-1bfe499643ce.png)

Acabo de subir uma alteração. Ao invés de reduce/2, estou utilizando reduce/3, com um acumulador default.

2022-10-08 20:10 UTC, fernanduandrade commented
consegui rodar, mas o resultado saiu diferente
<img width="920" alt="image" src="https://user-images.githubusercontent.com/58053397/194726167-7909699b-bad8-4046-aece-5fa47cedbf71.png">

2022-10-08 20:26 UTC, digzom commented
> consegui rodar, mas o resultado saiu diferente
> <img width="920" alt="image" src="https://user-images.githubusercontent.com/58053397/194726167-7909699b-bad8-4046-aece-5fa47cedbf71.png">
> 

Vou checar

2022-10-09 09:28 UTC, digzom commented
@Cyytrus no seu ambiente tem o mesmo comportamento?

2022-10-09 10:00 UTC, fernanduandrade commented
@Cyytrus alquimista ajuda nois ae kkkkk

2022-10-09 12:29 UTC, Cyytrus commented
Vou rodar aq assim q ir pro pc 🤪

2022-10-09 17:49 UTC, fernanduandrade commented
no windows tá bugando, meus colegas testaram em uma ide online e foi, entao vou aprovar

2022-10-09 17:50 UTC, fernanduandrade approved these changes

2022-10-09 17:50 UTC, merged

2022-10-09 22:39 UTC, digzom commented
> no windows tá bugando, meus colegas testaram em uma ide online e foi, entao vou aprovar

Agora me bateu curiosidade. Vou pegar uma VM windows da azure e testar lá hehe