Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #577
Opened 2022-10-06 21:42 UTC by IagoAntunes

2022-10-06 22:51 UTC, alissongdev requested changes
Os arquivos estão na pasta do desafio 1 em vez do 0.

2022-10-06 22:55 UTC, g-101 approved these changes
obrigado @alissongdev

2022-10-06 22:56 UTC, g-101 requested changes
a branch não bate com o desafio

2022-10-07 12:05 UTC, IagoAntunes commented
@g-101 @alissongdev 

Arrumado.

2022-10-07 13:32 UTC, g-101 approved these changes

2022-10-07 14:22 UTC, alissongdev approved these changes

2022-10-07 14:22 UTC, merged