Finalizando o desafio 3
he4rt/he4rtoberfest-2022 pull request #600
Opened 2022-10-06 23:44 UTC by joaooliveira247

2022-10-07 02:36 UTC, Luisnadachi requested changes
Salve virusxdrj, quando fui rodar seu codigo aqui apresentou o seguinte erro: 
![image](https://user-images.githubusercontent.com/51420622/194456150-6de5b624-1e39-46c8-b23f-acec2a4b3935.png)

2022-10-07 15:46 UTC, joaooliveira247 commented
https://imgur.com/kMFFLhO

2022-10-07 19:55 UTC, 1pride approved these changes
Exceto a parte de não especificar que precisaria da versão 3.10 do python o resto está certo.

2022-10-08 06:53 UTC, Luisnadachi approved these changes

2022-10-08 06:53 UTC, merged