Finalizando desafio 3
he4rt/he4rtoberfest-2022 pull request #656
Opened 2022-10-07 14:47 UTC by raffreitas

2022-10-07 16:42 UTC, edurevsky approved these changes
Testei o código e todas as entradas e saídas estavam **ok**.

Apenas senti falta de alguns prints na hora de inserir as entradas.

2022-10-07 16:51 UTC, edurevsky commented
Mas note que, se por exemplo, eu inserir um valor que não forma triângulo, ele pode acabar caindo no if do ISOSCELES caso tenha 2 lados iguais

2022-10-07 16:57 UTC, edurevsky requested changes

2022-10-07 16:57 UTC, edurevsky commented on challenges/3-tipos-de-triangulo/cpp/raffreitas/types-of-triangles.cpp
> +    cout << "NAO FORMA TRIANGULO" << endl;
Talvez um return aqui resolva esse problema.

2022-10-07 22:20 UTC, edurevsky approved these changes

2022-10-08 12:29 UTC, fernanduandrade approved these changes
output coreto

2022-10-08 12:29 UTC, merged