Finalizando o desafio 3
he4rt/he4rtoberfest-2022 pull request #664
Opened 2022-10-07 16:19 UTC by Nicolas-Formenton

2022-10-07 17:33 UTC, edurevsky requested changes
Testei o código e com as entradas 5,0 7,0 2,0 imprimiu:

_Não forma triângulo
Triângulo Obtusângulo_

2022-10-07 19:17 UTC, Nicolas-Formenton commented
Agora funcionou, tinha que reorganizar os if/else. Valeuu!

2022-10-07 19:35 UTC, edurevsky requested changes

2022-10-07 19:35 UTC, edurevsky commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Abrir um escopo nesse if e adicionar um return vai resolver mais um problema.

2022-10-07 19:35 UTC, edurevsky commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Se eu entrar com um valor que não forma um triângulo e tem 2 lados iguais como: 12,0 2,0 2,0, vai mostrar que é Isosceles

2022-10-07 20:46 UTC, Nicolas-Formenton commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Vou confessar que não entendi como eu abriria um escopo no próprio if rs... Seria fazer uma classe própria para esse if exclusivamente? e então retorna-lo?!

Se puder me explicar melhor, agradeceria.

2022-10-07 22:16 UTC, edurevsky commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
algo assim:

```java
if (A >= B + C) { // Abrindo um escopo
    System.out.println("Não forma triângulo");
    return; // A função main acabaria aqui por causa do return
}
```

2022-10-07 22:23 UTC, edurevsky commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Na real acho que o correto seria "abrir um bloco", acabei falando errado ali.

2022-10-08 00:07 UTC, Nicolas-Formenton commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Ah sim, acredito ser escopo mesmo, eu que não raciocinei, agora vendo faz sentido. 
Testei aqui e funcionou, vou commitar, só não entendi muito bem o por que com o return funciona e sem não, pode me explicar por favor?

2022-10-08 00:30 UTC, edurevsky commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Pois passando as entradas 12,0 2,0 2,0, por exemplo, ele vai passar pelo primeiro if, que é o de "não forma triângulo" e vai continuar indo nos outros if's.
Com esse return, caso as entradas passadas não formem um triângulo, ele vai fazer a função main parar de ser executada ali.

2022-10-08 00:39 UTC, edurevsky approved these changes

2022-10-08 03:45 UTC, Nicolas-Formenton commented on challenges/3-tipos-de-triangulo/java/nformenton/TiposDeTriangulo.java
>          if(A >= B + C) System.out.println("Não forma triangulo");
Entendi, ele "somaria" então o resultado dos sout's...
Obrigado!!

2022-10-08 12:33 UTC, fernanduandrade approved these changes
output correto

2022-10-08 12:36 UTC, fernanduandrade approved these changes
testado e outpout correto

2022-10-08 12:36 UTC, merged