Challenges/6/c#/marcosferreira17
he4rt/he4rtoberfest-2022 pull request #670
Opened 2022-10-07 17:15 UTC by MarcosFerreira17

2022-10-07 20:16 UTC, maikella commented
![image](https://user-images.githubusercontent.com/97262283/194645963-82dcf01d-b1a7-4b4b-8d3d-08957d20eacd.png)
[MarcosFerreira17](https://github.com/MarcosFerreira17), firmesa? man, remova os diretórios relacionados a outros desafios. apenas um por PR.

2022-10-07 22:47 UTC, fernanduandrade requested changes
na pr deve ir apenas arquivos relacionados ao desafio 6 :<

2022-10-09 10:03 UTC, fernanduandrade commented
cara tá bem estranho, se eu aprovar vai tirar o que vc submeteu no desafio 0
teria como criar uma nova branch a partir da main?

2022-10-09 17:50 UTC, MarcosFerreira17 commented
Pode exluir, eu tenho dois helloworld mergeados.

2022-10-09 17:53 UTC, fernanduandrade commented
blz, qualquer coisa vou dar um revert

2022-10-09 17:54 UTC, fernanduandrade approved these changes

2022-10-09 17:54 UTC, merged