Finalizando Desafio
he4rt/he4rtoberfest-2022 pull request #675
Opened 2022-10-07 18:05 UTC by JSombra

2022-10-07 20:18 UTC, maikella commented
![image](https://user-images.githubusercontent.com/97262283/194646166-a7e228b1-f52b-4edd-a486-c9d29934faca.png)
[JSombra](https://github.com/JSombra), beleza man? remova os diretórios relacionados a outros desafios. apenas um por PR.

2022-10-07 22:49 UTC, matheusth requested changes
como o @maikella disse, apenas um desafio por pull request.

2022-10-07 22:57 UTC, JSombra commented
puts, não tinha visto. Ainda to aprendendo git. Nesse caso eu desfaço o commit?

2022-10-07 23:17 UTC, matheusth commented
é mais facil remover a pasta do desafio um e fazer um novo commit no branch e da push para ele, ai o pull request aqui atualiza automaticamente.

2022-10-08 16:29 UTC, JSombra commented
acho que agora foi

2022-10-08 16:30 UTC, JSombra commented
Nesses casos, eu solicito a revisão novamente no PR certo?

2022-10-08 17:08 UTC, matheusth approved these changes

2022-10-08 17:25 UTC, matheusth commented
> Nesses casos, eu solicito a revisão novamente no PR certo?

é bom pq ai a notificação aparece em uma box separada aqui.

2022-10-08 17:27 UTC, merged