Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #732
Opened 2022-10-08 04:36 UTC by WillianAlbeche

Olá!

2022-10-08 05:36 UTC, Luisnadachi requested changes
Salve [WillianAlbeche](https://github.com/WillianAlbeche), você está subindo vários arquivos em diferentes pastas no projeto.

2022-10-09 12:07 UTC, kelion-aquino commented on challenges/0-hello-world/swift/WillianAlbeche/HelloWorld/helloWorld.swift
> +print("Hello World!! \nLembre: Nada é impossivel, a gente só não sabe fazer isso ainda!")
Opa primo, tranquilo? O Output do desafio deve seguir o seguinte padrão:
```bash
Hello He4rtoberfest
```
Obs.: Caso tenha dúvidas em relação ao desafio, sempre dá uma olhada no [readme.md](https://github.com/he4rt/he4rtoberfest-2022/tree/main/challenges/0-hello-world#desafio-0)

2022-10-09 12:18 UTC, kelion-aquino reviewed
No caso dos arquivos que o @Luisnadachi comentou, só rodar os seguintes comandos na sua branch local:
``` bash
git rm --cached .DS_Store

git add .

git commit -m "Fix - Remove .DS_Store from current directories"

git push origin WillianAlbeche:challenges/0/Swift/WillianAlbeche
```

2022-10-10 01:06 UTC, WillianAlbeche commented on challenges/0-hello-world/swift/WillianAlbeche/HelloWorld/helloWorld.swift
> +print("Hello World!! \nLembre: Nada é impossivel, a gente só não sabe fazer isso ainda!")
Olá! tudo certo por aqui, obrigado pelo aviso e pelas dicas, acredito que agora esteja nos conformes, qualquer coisa me avisem e mais uma vez, obrigado pela ajuda!

2022-10-10 04:58 UTC, Luisnadachi commented
Salve [WillianAlbeche](https://github.com/WillianAlbeche), você pediu requeste para eu verificar e ainda consta que você está enviando varios arquivos.

2022-10-10 13:08 UTC, closed without merging