Finalizando o desafio
he4rt/he4rtoberfest-2022 pull request #839
Opened 2022-10-09 18:07 UTC by kayehol

2022-10-09 19:19 UTC, alissongdev approved these changes

2022-10-09 19:24 UTC, alissongdev requested changes
Peço que adeque a estrutura de pastas do seu desafio de `challenges/1/php/kayehol` para `challenges/1-produto-simples/php/kayehol`.

2022-10-10 00:36 UTC, kayehol commented
@alissongdev eu tinha feito como vc falou antes e me falaram pra fazer como challenges/id/lang/user. qual é o certo?

2022-10-10 01:06 UTC, alissongdev commented
> @alissongdev eu tinha feito como vc falou antes e me falaram pra fazer como challenges/id/lang/user. qual é o certo?

O nome da sua branch está correto, mas a estrutura de pastas onde você subiu o desafio, não. Note que você está criando um novo diretório com o nome `1/php` em vez de adicionar o seu desafio dentro do diretório existente `1-produto-simples/php`.

2022-10-10 02:17 UTC, kayehol commented
Entendi. Isso precisa ser corrigido no README então, lá tá assim:

 _Crie uma pasta da linguagem que você escolheu no diretório challenges/id_challenge/lang/
Depois dentro desta pasta lang crie a pasta com seu nickname ficando assim challenges/id_challenge/lang/nickname_

2022-10-10 17:46 UTC, alissongdev commented
> Entendi. Isso precisa ser corrigido no README então, lá tá assim:
> 
> _Crie uma pasta da linguagem que você escolheu no diretório challenges/id_challenge/lang/ Depois dentro desta pasta lang crie a pasta com seu nickname ficando assim challenges/id_challenge/lang/nickname_

Está um pouco dúbio mesmo, mas não estamos tendo muitos problemas com isso. Se achar válido, pode abrir uma issue para discutirmos essa alteração :)

2022-10-10 17:47 UTC, merged