Finalizando desafio
he4rt/he4rtoberfest-2022 pull request #896
Opened 2022-10-10 20:59 UTC by I-Am-Not-Lucas

2022-10-10 22:32 UTC, Luisnadachi commented
Salve [I-Am-Not-Lucas](https://github.com/I-Am-Not-Lucas), suba somente um desafio por PR.

2022-10-10 23:13 UTC, I-Am-Not-Lucas commented
salve nadachi, subiu mais de um?? eu fui mandando um por um, seria pq mandei vários seguidos?

2022-10-11 00:10 UTC, g-101 requested changes
Aguardando alteração.
Prazo 48h.

2022-10-11 05:33 UTC, Luisnadachi commented
> salve nadachi, subiu mais de um?? eu fui mandando um por um, seria pq mandei vários seguidos?

possivelmente você deve ter feito git checkout -b a cada branch que vc criava, no geral vc tem que sempre voltar pra sua branch main e de la criar uma nova branch de desafio pq se n vai acontecer isso

2022-10-11 11:51 UTC, I-Am-Not-Lucas commented
Eu posso através do próprio github eliminar so arquivos, ou tenho que refazer a branch , e abrir um novo PR fechando esse?

2022-10-11 14:17 UTC, closed without merging